// Hardcoded sample data for Word of the Day series

const wordData = [
  {
    "word": "big",
    "partOfSpeech": "adjective",
    "pronunciation":"none",
    "meaning": "large in size or amount",
    "sentence": "The elephant is a big animal.",
    "synonyms": "large",
    "homonyms": "none",
    "antonyms": "small",
    "rhyming": "wig",
    "plural": "none"
  },
  {
    "word": "run",
    "partOfSpeech": "verb",
    "meaning": "to move quickly on foot using your legs",
    "sentence": "We run to the playground every day!",
    "synonyms": "dash",
    "homonyms": "none",
    "antonyms": "walk",
    "rhyming": "fun",
    "plural": "runs"
  },
  {
    "word": "sun",
    "partOfSpeech": "noun",
    "meaning": "the star that lights up the sky in the daytime",
    "sentence": "The sun is shining bright.",
    "synonyms": "star",
    "homonyms": "son",
    "antonyms": "moon",
    "rhyming": "fun",
    "plural": "suns"
  },
  {
    "word": "happy",
    "partOfSpeech": "adjective",
    "meaning": "feeling or showing pleasure",
    "sentence": "She was happy on her birthday.",
    "synonyms": "joyful",
    "homonyms": "hoppy",
    "antonyms": "sad",
    "rhyming": "snappy",
    "plural": "happies"
  },
  {
    "word": "cat",
    "partOfSpeech": "noun",
    "meaning": "a small domesticated animal with fur that says 'meow'",
    "sentence": "The cat chased the ball.",
    "synonyms": "kitten",
    "homonyms": "kat",
    "antonyms": "dog",
    "rhyming": "hat",
    "plural": "cats"
  },
  {
    "word": "jump",
    "partOfSpeech": "verb",
    "meaning": "to push yourself off the ground and into the air",
    "sentence": "Can you jump as high as a frog?",
    "synonyms": "leap",
    "homonyms": "none",
    "antonyms": "sit",
    "rhyming": "bump",
    "plural": "jumps"
  },
  {
    "word": "red",
    "partOfSpeech": "adjective",
    "meaning": "a color like an apple or a stop sign",
    "sentence": "She wore a red dress.",
    "synonyms": "crimson",
    "homonyms": "read",
    "antonyms": "blue",
    "rhyming": "bed",
    "plural": "reds"
  },
  {
      "word": "book",
      "partOfSpeech": "noun",
      "meaning": "a set of printed pages with words or pictures",
      "sentence": "She reads a book every night.",
      "synonyms": "volume",
      "homonyms": "none",
      "antonyms": "none",
      "rhyming": "look",
      "plural": "books"
    },
  {
    "word": "play",
    "partOfSpeech": "verb",
    "meaning": "to engage in a fun activity",
    "sentence": "The children play in the garden.",
    "synonyms": "frolic",
    "homonyms": "none",
    "antonyms": "work",
    "rhyming": "day",
    "plural": "plays"
  },
  {
    "word": "tree",
    "partOfSpeech": "noun",
    "meaning": "a tall plant with a trunk and leaves",
    "sentence": "The tree has green leaves.",
    "synonyms": "plant",
    "homonyms": "none",
    "antonyms": "none",
    "rhyming": "free",
    "plural": "trees"
  },
  {
    "word": "ball",
    "partOfSpeech": "noun",
    "meaning": "a round object used for playing",
    "sentence": "She threw the ball to her friend.",
    "synonyms": "sphere",
    "homonyms": "bawl",
    "antonyms": "none",
    "rhyming": "call",
    "plural": "balls"
  },
  {
    "word": "fish",
    "partOfSpeech": "noun",
    "meaning": "a water-dwelling animal",
    "sentence": "We saw a fish in the pond.",
    "synonyms": "trout",
    "homonyms": "phish",
    "antonyms": "bird",
    "rhyming": "dish",
    "plural": "fish"
  },
  {
    "word": "blue",
    "partOfSpeech": "adjective",
    "meaning": "the color of the sky and or the ocean",
    "sentence": "She drew a blue sky.",
    "synonyms": "azure",
    "homonyms": "blew",
    "antonyms": "red",
    "rhyming": "true",
    "plural": "blues"
  },
  {
    "word": "star",
    "partOfSpeech": "noun",
    "meaning": "a bright point in the sky at night",
    "sentence": "The star twinkled at night.",
    "synonyms": "sun",
    "homonyms": "none",
    "antonyms": "darkness",
    "rhyming": "car",
    "plural": "stars"
  },
  {
    "word": "dog",
    "partOfSpeech": "noun",
    "meaning": "a domesticated animal that barks",
    "sentence": "The dog wagged its tail.",
    "synonyms": "puppy",
    "homonyms": "dawg",
    "antonyms": "cat",
    "rhyming": "frog",
    "plural": "dogs"
  },
  {
    "word": "cake",
    "partOfSpeech": "noun",
    "meaning": "a sweet baked food often for birthdays",
    "sentence": "We ate chocolate cake at the party.",
    "synonyms": "pastry",
    "homonyms": "kake",
    "antonyms": "bread",
    "rhyming": "bake",
    "plural": "cakes"
  },
  {
    "word": "brave",
    "partOfSpeech": "adjective",
    "meaning": "showing courage in the face of danger",
    "sentence": "The brave firefighter saved the cat.",
    "synonyms": "courageous",
    "homonyms": "none",
    "antonyms": "cowardly",
    "rhyming": "cave",
    "plural": "none"
  },
  {
    "word": "whisper",
    "partOfSpeech": "verb",
    "meaning": "to speak very softly",
    "sentence": "She whispered a secret to her friend.",
    "synonyms": "murmur",
    "homonyms": "none",
    "antonyms": "shout",
    "rhyming": "sister",
    "plural": "whispers"
  },
  {
    "word": "gentle",
    "partOfSpeech": "adjective",
    "meaning": "kind, soft, or mild in manner",
    "sentence": "Her gentle touch calmed the puppy.",
    "synonyms": "tender",
    "homonyms": "none",
    "antonyms": "harsh",
    "rhyming": "simple",
    "plural": "none"
  },
  {
    "word": "forest",
    "partOfSpeech": "noun",
    "meaning": "a large area covered chiefly with trees",
    "sentence": "The forest was full of tall trees.",
    "synonyms": "woods",
    "homonyms": "none",
    "antonyms": "desert",
    "rhyming": "chorist",
    "plural": "forests"
  },
  {
    "word": "clever",
    "partOfSpeech": "adjective",
    "meaning": "smart and quick-thinking",
    "sentence": "The clever fox tricked the crow.",
    "synonyms": "intelligent",
    "homonyms": "none",
    "antonyms": "foolish",
    "rhyming": "never",
    "plural": "none"
  },
  {
    "word": "journey",
    "partOfSpeech": "noun",
    "meaning": "a trip from one place to another",
    "sentence": "They went on a long journey to the mountains.",
    "synonyms": "trip",
    "homonyms": "none",
    "antonyms": "stay",
    "rhyming": "attorney",
    "plural": "journeys"
  },
  {
    "word": "curious",
    "partOfSpeech": "adjective",
    "meaning": "eager to know or learn something",
    "sentence": "The curious child asked many questions.",
    "synonyms": "inquisitive",
    "homonyms": "none",
    "antonyms": "indifferent",
    "rhyming": "furious",
    "plural": "none"
  },
  {
    "word": "mountain",
    "partOfSpeech": "noun",
    "meaning": "a very high hill",
    "sentence": "They climbed the tall mountain.",
    "synonyms": "peak",
    "homonyms": "none",
    "antonyms": "valley",
    "rhyming": "fountain",
    "plural": "mountains"
  },
  {
    "word": "silent",
    "partOfSpeech": "adjective",
    "meaning": "not making any sound",
    "sentence": "The classroom was silent during the test.",
    "synonyms": "quiet",
    "homonyms": "none",
    "antonyms": "noisy",
    "rhyming": "violent",
    "plural": "none"
  },
  {
    "word": "wonder",
    "partOfSpeech": "noun",
    "meaning": "a feeling of amazement",
    "sentence": "The stars filled her with wonder.",
    "synonyms": "awe",
    "homonyms": "none",
    "antonyms": "boredom",
    "rhyming": "thunder",
    "plural": "wonders"
  },
  {
    "word": "bright",
    "partOfSpeech": "adjective",
    "meaning": "giving off much light",
    "sentence": "The stars looked bright in the sky.",
    "synonyms": "radiant",
    "homonyms": "none",
    "antonyms": "dim",
    "rhyming": "light",
    "plural": "brights"
  },
  {
    "word": "laugh",
    "partOfSpeech": "verb",
    "meaning": "to make a happy sound with your mouth",
    "sentence": "He laughed at the joke.",
    "synonyms": "giggle",
    "homonyms": "none",
    "antonyms": "cry",
    "rhyming": "half",
    "plural": "laughs"
  },
  {
    "word": "dizzy",
    "partOfSpeech": "adjective",
    "meaning": "feeling like spinning",
    "sentence": "He felt dizzy after spinning around.",
    "synonyms": "lightheaded",
    "homonyms": "none",
    "antonyms": "steady",
    "rhyming": "busy",
    "plural": "dizzies"
  },
  {
    "word": "shine",
    "partOfSpeech": "verb",
    "meaning": "to give off or reflect light",
    "sentence": "The stars shine at night.",
    "synonyms": "glow",
    "homonyms": "none",
    "antonyms": "dim",
    "rhyming": "fine",
    "plural": "shines"
  },
  {
    "word": "gift",
    "partOfSpeech": "noun",
    "meaning": "a present",
    "sentence": "He gave her a beautiful gift.",
    "synonyms": "present",
    "homonyms": "lift",
    "antonyms": "none",
    "rhyming": "shift",
    "plural": "gifts"
  },
  {
    "word": "mild",
    "partOfSpeech": "adjective",
    "meaning": "not too strong",
    "sentence": "The weather was mild today.",
    "synonyms": "gentle",
    "homonyms": "wild",
    "antonyms": "harsh",
    "rhyming": "child",
    "plural": "milds"
  },
  {
    "word": "climb",
    "partOfSpeech": "verb",
    "meaning": "to go up something",
    "sentence": "They love to climb the big tree.",
    "synonyms": "ascend",
    "homonyms": "none",
    "antonyms": "descend",
    "rhyming": "rhyme",
    "plural": "climbs"
  },
  {
    "word": "deep",
    "partOfSpeech": "adjective",
    "meaning": "extending far down",
    "sentence": "The lake was very deep.",
    "synonyms": "profound",
    "homonyms": "jeep",
    "antonyms": "shallow",
    "rhyming": "sleep",
    "plural": "deeps"
  },
  {
    "word": "kind",
    "partOfSpeech": "adjective",
    "meaning": "being nice to others",
    "sentence": "She was kind to her little brother.",
    "synonyms": "generous",
    "homonyms": "none",
    "antonyms": "mean",
    "rhyming": "mind",
    "plural": "kinds"
  },
  {
    "word": "fast",
    "partOfSpeech": "adjective",
    "meaning": "moving quickly",
    "sentence": "The car was very fast.",
    "synonyms": "quick",
    "homonyms": "none",
    "antonyms": "slow",
    "rhyming": "last",
    "plural": "fasts"
  },
  {
    "word": "explore",
    "partOfSpeech": "verb",
    "meaning": "to travel and discover new places",
    "sentence": "They explore the forest for adventure.",
    "synonyms": "investigate",
    "homonyms": "none",
    "antonyms": "ignore",
    "rhyming": "more",
    "plural": "explores"
  },
  {
    "word": "river",
    "partOfSpeech": "noun",
    "meaning": "a large flowing body of water",
    "sentence": "The river runs through the valley.",
    "synonyms": "stream",
    "homonyms": "none",
    "antonyms": "none",
    "rhyming": "giver",
    "plural": "rivers"
  },
  {
    "word": "build",
    "partOfSpeech": "verb",
    "meaning": "to construct by putting parts together",
    "sentence": "They build a sandcastle on the beach.",
    "synonyms": "construct",
    "homonyms": "none",
    "antonyms": "destroy",
    "rhyming": "filled",
    "plural": "builds"
  },
  {
    "word": "cloud",
    "partOfSpeech": "noun",
    "meaning": "a mass of water vapor in the sky",
    "sentence": "The cloud covered the sun.",
    "synonyms": "mist",
    "homonyms": "none",
    "antonyms": "none",
    "rhyming": "loud",
    "plural": "clouds"
  },
  {
    "word": "swift",
    "partOfSpeech": "adjective",
    "meaning": "moving very fast",
    "sentence": "The cheetah is a swift animal.",
    "synonyms": "speedy",
    "homonyms": "none",
    "antonyms": "sluggish",
    "rhyming": "gift",
    "plural": "swifts"
  },
  {
    "word": "glow",
    "partOfSpeech": "verb",
    "meaning": "to shine with a steady light",
    "sentence": "Fireflies glow in the dark.",
    "synonyms": "shine",
    "homonyms": "none",
    "antonyms": "fade",
    "rhyming": "snow",
    "plural": "glows"
  },
  {
    "word": "giant",
    "partOfSpeech": "noun",
    "meaning": "a very large and powerful being",
    "sentence": "The story was about a friendly giant.",
    "synonyms": "colossus",
    "homonyms": "none",
    "antonyms": "dwarf",
    "rhyming": "pliant",
    "plural": "giants"
  },
  {
    "word": "shadow",
    "partOfSpeech": "noun",
    "meaning": "a dark shape caused by a light being blocked",
    "sentence": "My shadow follows me on sunny days.",
    "synonyms": "silhouette",
    "homonyms": "none",
    "antonyms": "light",
    "rhyming": "meadow",
    "plural": "shadows"
  },
  {
    "word": "honest",
    "partOfSpeech": "adjective",
    "meaning": "always telling the truth",
    "sentence": "It is important to be honest.",
    "synonyms": "truthful",
    "homonyms": "none",
    "antonyms": "dishonest",
    "rhyming": "modest",
    "plural": "none"
  },
  {
    "word": "search",
    "partOfSpeech": "verb",
    "meaning": "to look carefully for something",
    "sentence": "They search for treasure in the cave.",
    "synonyms": "seek",
    "homonyms": "none",
    "antonyms": "find",
    "rhyming": "perch",
    "plural": "searches"
  },
  {
    "word": "village",
    "partOfSpeech": "noun",
    "meaning": "a small community in a rural area",
    "sentence": "The village has a small school.",
    "synonyms": "hamlet",
    "homonyms": "none",
    "antonyms": "city",
    "rhyming": "image",
    "plural": "villages"
  },
  {
    "word": "elusive",
    "partOfSpeech": "adjective",
    "meaning": "difficult to find, catch, or achieve",
    "sentence": "The meaning of the poem remained elusive.",
    "synonyms": "intangible",
    "homonyms": "none",
    "antonyms": "obvious",
    "rhyming": "exclusive",
    "plural": "none"
  },
  {
    "word": "vigilant",
    "partOfSpeech": "adjective",
    "meaning": "keeping careful watch for danger",
    "sentence": "The guards remained vigilant throughout the night.",
    "synonyms": "watchful",
    "homonyms": "none",
    "antonyms": "careless",
    "rhyming": "diligent",
    "plural": "none"
  },
  {
    "word": "precise",
    "partOfSpeech": "adjective",
    "meaning": "marked by exactness and accuracy",
    "sentence": "His instructions were clear and precise.",
    "synonyms": "accurate",
    "homonyms": "none",
    "antonyms": "vague",
    "rhyming": "concise",
    "plural": "none"
  },
  {
    "word": "eloquent",
    "partOfSpeech": "adjective",
    "meaning": "fluent or persuasive in speaking or writing",
    "sentence": "Her speech was both eloquent and moving.",
    "synonyms": "articulate",
    "homonyms": "none",
    "antonyms": "inarticulate",
    "rhyming": "subsequent",
    "plural": "none"
  },
  {
    "word": "serene",
    "partOfSpeech": "adjective",
    "meaning": "calm, peaceful, and untroubled",
    "sentence": "The lake was serene in the early morning light.",
    "synonyms": "tranquil",
    "homonyms": "scene",
    "antonyms": "turbulent",
    "rhyming": "marine",
    "plural": "none"
  },
  {
    "word": "resilient",
    "partOfSpeech": "adjective",
    "meaning": "able to recover quickly",
    "sentence": "She was resilient after the setback.",
    "synonyms": "tough",
    "homonyms": "none",
    "antonyms": "fragile",
    "rhyming": "persistent",
    "plural": "none"
  },
  {
    "word": "phenomenon",
    "partOfSpeech": "noun",
    "meaning": "an extraordinary event",
    "sentence": "The aurora is a natural phenomenon.",
    "synonyms": "marvel",
    "homonyms": "none",
    "antonyms": "normality",
    "rhyming": "none",
    "plural": "phenomena"
  },
  {
    "word": "meticulous",
    "partOfSpeech": "adjective",
    "meaning": "very careful and precise",
    "sentence": "He was meticulous in his work.",
    "synonyms": "thorough",
    "homonyms": "none",
    "antonyms": "careless",
    "rhyming": "ridiculous",
    "plural": "none"
  },
  {
    "word": "ambiguous",
    "partOfSpeech": "adjective",
    "meaning": "having more than one possible meaning",
    "sentence": "The answer was ambiguous and confused the class.",
    "synonyms": "unclear",
    "homonyms": "none",
    "antonyms": "explicit",
    "rhyming": "contiguous",
    "plural": "none"
  },
  {
    "word": "benevolent",
    "partOfSpeech": "adjective",
    "meaning": "well meaning and kindly",
    "sentence": "The benevolent teacher helped every student.",
    "synonyms": "kind",
    "homonyms": "none",
    "antonyms": "malevolent",
    "rhyming": "relevant",
    "plural": "none"
  },
  {
    "word": "juxtapose",
    "partOfSpeech": "verb",
    "meaning": "place side by side for contrast",
    "sentence": "The artist juxtaposed light and dark colors.",
    "synonyms": "contrast",
    "homonyms": "none",
    "antonyms": "separate",
    "rhyming": "oppose",
    "plural": "juxtaposes"
  },
  {
    "word": "ephemeral",
    "partOfSpeech": "adjective",
    "meaning": "lasting a short time",
    "sentence": "The joy was ephemeral.",
    "synonyms": "fleeting",
    "homonyms": "none",
    "antonyms": "permanent",
    "rhyming": "femoral",
    "plural": "none"
  },
  {
    "word": "pragmatic",
    "partOfSpeech": "adjective",
    "meaning": "practical and realistic",
    "sentence": "She took a pragmatic approach.",
    "synonyms": "sensible",
    "homonyms": "none",
    "antonyms": "idealistic",
    "rhyming": "charismatic",
    "plural": "none"
  },
  {
    "word": "ubiquitous",
    "partOfSpeech": "adjective",
    "meaning": "present everywhere",
    "sentence": "Smartphones are ubiquitous today.",
    "synonyms": "omnipresent",
    "homonyms": "none",
    "antonyms": "rare",
    "rhyming": "none",
    "plural": "none"
  },
  {
    "word": "illusion",
    "partOfSpeech": "noun",
    "meaning": "a false idea or belief",
    "sentence": "The magician created an illusion of floating.",
    "synonyms": "mirage",
    "homonyms": "elusion",
    "antonyms": "reality",
    "rhyming": "conclusion",
    "plural": "illusions"
  },
  {
    "word": "marvel",
    "partOfSpeech": "noun",
    "meaning": "something wonderful or surprising",
    "sentence": "The new building was a marvel of design.",
    "synonyms": "wonder",
    "homonyms": "none",
    "antonyms": "normalcy",
    "rhyming": "carvel",
    "plural": "marvels"
  },
  {
    "word": "obscure",
    "partOfSpeech": "adjective",
    "meaning": "not clearly understood",
    "sentence": "His explanation was obscure and confusing.",
    "synonyms": "unclear",
    "homonyms": "none",
    "antonyms": "clear",
    "rhyming": "secure",
    "plural": "none"
  },
  {
    "word": "diligent",
    "partOfSpeech": "adjective",
    "meaning": "careful and hard-working",
    "sentence": "She was diligent in her studies.",
    "synonyms": "industrious",
    "homonyms": "none",
    "antonyms": "lazy",
    "rhyming": "intelligent",
    "plural": "none"
  },
  {
    "word": "elaborate",
    "partOfSpeech": "adjective",
    "meaning": "involving many details",
    "sentence": "The plan was elaborate and well-thought-out.",
    "synonyms": "detailed",
    "homonyms": "none",
    "antonyms": "simple",
    "rhyming": "collaborate",
    "plural": "none"
  },
  {
    "word": "absurd",
    "partOfSpeech": "adjective",
    "meaning": "wildly unreasonable or ridiculous",
    "sentence": "It was absurd to suggest they could fly.",
    "synonyms": "ridiculous",
    "homonyms": "observed",
    "antonyms": "reasonable",
    "rhyming": "bird",
    "plural": "none"
  },
  {
    "word": "vague",
    "partOfSpeech": "adjective",
    "meaning": "unclear or indistinct",
    "sentence": "His response was vague and unhelpful.",
    "synonyms": "uncertain",
    "homonyms": "plague",
    "antonyms": "precise",
    "rhyming": "plague",
    "plural": "none"
  },
  {
    "word": "analyze",
    "partOfSpeech": "verb",
    "meaning": "to examine in detail to understand or explain",
    "sentence": "Scientists analyze data to find patterns.",
    "synonyms": "examine",
    "homonyms": "none",
    "antonyms": "ignore",
    "rhyming": "realize",
    "plural": "analyzes"
  },
  {
    "word": "liberty",
    "partOfSpeech": "noun",
    "meaning": "the state of being free from oppression",
    "sentence": "The statue symbolizes liberty for all.",
    "synonyms": "freedom",
    "homonyms": "none",
    "antonyms": "captivity",
    "rhyming": "property",
    "plural": "liberties"
  },
  {
    "word": "intricate",
    "partOfSpeech": "adjective",
    "meaning": "very detailed or complicated",
    "sentence": "The intricate design amazed everyone.",
    "synonyms": "complex",
    "homonyms": "none",
    "antonyms": "simple",
    "rhyming": "delicate",
    "plural": "none"
  },
  {
    "word": "debate",
    "partOfSpeech": "verb",
    "meaning": "to discuss or argue formally about a topic",
    "sentence": "They debate the best solution in class.",
    "synonyms": "argue",
    "homonyms": "none",
    "antonyms": "agree",
    "rhyming": "fate",
    "plural": "debates"
  },
  {
    "word": "horizon",
    "partOfSpeech": "noun",
    "meaning": "the line where the earth and sky appear to meet",
    "sentence": "The ship sailed toward the horizon.",
    "synonyms": "skyline",
    "homonyms": "none",
    "antonyms": "none",
    "rhyming": "poison",
    "plural": "horizons"
  },
  {
    "word": "persist",
    "partOfSpeech": "verb",
    "meaning": "to continue firmly despite difficulty",
    "sentence": "He will persist until he succeeds.",
    "synonyms": "endure",
    "homonyms": "none",
    "antonyms": "quit",
    "rhyming": "assist",
    "plural": "persists"
  },
  {
    "word": "culture",
    "partOfSpeech": "noun",
    "meaning": "the beliefs and customs of a group",
    "sentence": "The festival celebrates local culture.",
    "synonyms": "tradition",
    "homonyms": "none",
    "antonyms": "none",
    "rhyming": "vulture",
    "plural": "cultures"
  },
  {
    "word": "innovate",
    "partOfSpeech": "verb",
    "meaning": "to introduce new ideas or methods",
    "sentence": "Companies innovate to stay competitive.",
    "synonyms": "create",
    "homonyms": "none",
    "antonyms": "copy",
    "rhyming": "create",
    "plural": "innovates"
  },
  {
    "word": "serendipity",
    "partOfSpeech": "noun",
    "meaning": "the occurrence of happy events by chance",
    "sentence": "Finding an old friend in a new city was pure serendipity.",
    "synonyms": "fluke",
    "homonyms": "none",
    "antonyms": "misfortune",
    "rhyming": "activity",
    "plural": "serendipities"
  },
  {
    "word": "empathy",
    "partOfSpeech": "noun",
    "meaning": "the ability to understand and share the feelings of another",
    "sentence": "Showing empathy can help build strong friendships.",
    "synonyms": "compassion",
    "homonyms": "none",
    "antonyms": "apathy",
    "rhyming": "telepathy",
    "plural": "empathies"
  },
  {
    "word": "innovation",
    "partOfSpeech": "noun",
    "meaning": "a new idea, method, or device",
    "sentence": "Innovation drives progress in technology.",
    "synonyms": "invention",
    "homonyms": "none",
    "antonyms": "tradition",
    "rhyming": "station",
    "plural": "innovations"
  },
  {
    "word": "metaphor",
    "partOfSpeech": "noun",
    "meaning": "a figure of speech comparing two things without using 'like' or 'as'",
    "sentence": "She used a metaphor to describe her busy life as a circus.",
    "synonyms": "analogy",
    "homonyms": "none",
    "antonyms": "literal",
    "rhyming": "nevermore",
    "plural": "metaphors"
  },
  {
    "word": "persevere",
    "partOfSpeech": "verb",
    "meaning": "to keep trying despite difficulties",
    "sentence": "You must persevere when facing challenges.",
    "synonyms": "persist",
    "homonyms": "none",
    "antonyms": "quit",
    "rhyming": "volunteer",
    "plural": "perseveres"
  },
  {
    "word": "catalyst",
    "partOfSpeech": "noun",
    "meaning": "something that causes change",
    "sentence": "Her speech was a catalyst for action.",
    "synonyms": "stimulus",
    "homonyms": "none",
    "antonyms": "hindrance",
    "rhyming": "analyst",
    "plural": "catalysts"
  }
];

export default wordData;