const levelData = {
  "Class I & II": [
    { name: 'Rookie', tagline: 'Starting Strong, Learning Along!', 
      colors: ['from-red-500', 'via-pink-500', 'to-rose-500'],
      bgPattern: 'from-red-400/20 via-pink-400/20 to-rose-400/20',
      description: "Build confidence by learning the basics of English.",
      modules: ["Spelling", "Reading", "Pronunciation", "Vocabulary"],
      tips: ["Complete one activity daily", "Use flashcards to remember words", "Read aloud to improve pronunciation"],
      goal: "Rank up to Racer by mastering basic words and sentences!" },
    { name: 'Racer', tagline: 'Pacing with Skills, Chasing Next Goals!', 
      colors: ['from-amber-400', 'via-orange-500', 'to-red-500'],
      bgPattern: 'from-amber-400/20 via-orange-400/20 to-red-400/20',
      description: "Boost your speed and improve sentence formation.",
      modules: ["Grammar", "Writing", "S.H.A.R.P", "Listening"],
      tips: ["Practice simple sentence formation", "Listen to short stories", "Write basic sentences"],
      goal: "Become a Master by improving reading, writing, and speaking!" },
    { name: 'Master', tagline: 'Crafting Words, Winning Hearts!', 
      colors: ['from-emerald-400', 'via-teal-500', 'to-cyan-600'],
      bgPattern: 'from-emerald-400/20 via-teal-400/20 to-cyan-400/20',
      description: "Express yourself confidently with better writing and vocabulary.",
      modules: ["Writing", "Pronunciation", "Vocabulary", "Reading"],
      tips: ["Engage in creative writing exercises", "Use new vocabulary in daily speech", "Read picture books and tell stories"],
      goal: "Rank up to Prodigy by strengthening grammar and vocabulary!" },
    { name: 'Prodigy', tagline: 'Winning the Crowd, Making Everyone Proud!', 
      colors: ['from-violet-500', 'via-purple-600', 'to-fuchsia-600'],
      bgPattern: 'from-violet-400/20 via-purple-400/20 to-fuchsia-400/20',
      description: "Master advanced writing, grammar, and speaking skills for your level.",
      modules: ["S.H.A.R.P", "Listening", "Grammar", "Spelling"],
      tips: ["Listen to simple audiobooks", "Practice storytelling", "Master spelling patterns"],
      goal: "Achieve Wizard status by demonstrating fluency and confidence!" },
    { name: 'Wizard', tagline: 'A World of Words, at My Command!', 
      colors: ['from-indigo-600', 'via-purple-700', 'to-pink-700'],
      bgPattern: 'from-indigo-500/20 via-purple-500/20 to-pink-500/20',
      description: "You command the language with fluency, clarity, and expertise for your age!",
      modules: ["All Modules Combined", "Writing", "Grammar & Vocabulary", "Reading & Speaking"],
      tips: ["Engage in show-and-tell", "Write creative short stories", "Help classmates with reading"],
      goal: "Stay at Wizard Level & Beyond! Inspire others with your skills!" }
  ],
  "Class III to V": [
    { name: 'Rookie', tagline: 'Building Blocks for Excellence!', 
      colors: ['from-rose-500', 'via-red-500', 'to-pink-600'],
      bgPattern: 'from-rose-400/20 via-red-400/20 to-pink-400/20',
      description: "Develop stronger foundational English skills with proper structure.",
      modules: ["Grammar", "Reading", "Vocabulary", "Spelling"],
      tips: ["Practice basic sentence structures", "Read chapter books", "Build systematic word banks"],
      goal: "Rank up to Racer by forming well-structured sentences!" },
    { name: 'Racer', tagline: 'Accelerating Towards Mastery!', 
      colors: ['from-yellow-400', 'via-amber-500', 'to-orange-600'],
      bgPattern: 'from-yellow-400/20 via-amber-400/20 to-orange-400/20',
      description: "Advance vocabulary and develop structured writing abilities.",
      modules: ["Writing", "Listening", "S.H.A.R.P", "Pronunciation"],
      tips: ["Write detailed paragraphs", "Practice active listening", "Master word relationships"],
      goal: "Become a Master by refining writing and comprehension skills!" },
    { name: 'Master', tagline: 'Refining Language Proficiency!', 
      colors: ['from-green-500', 'via-emerald-600', 'to-teal-600'],
      bgPattern: 'from-green-400/20 via-emerald-400/20 to-teal-400/20',
      description: "Improve fluency and develop deeper text comprehension abilities.",
      modules: ["Reading", "Grammar", "Writing", "Vocabulary"],
      tips: ["Read diverse texts for comprehension", "Apply advanced grammar rules", "Expand academic vocabulary"],
      goal: "Rank up to Prodigy by mastering structured communication!" },
    { name: 'Prodigy', tagline: 'Becoming an English Expert!', 
      colors: ['from-blue-500', 'via-indigo-600', 'to-purple-600'],
      bgPattern: 'from-blue-400/20 via-indigo-400/20 to-purple-400/20',
      description: "Students analyze texts and articulate ideas with clarity and purpose.",
      modules: ["Listening", "Pronunciation", "Advanced Writing", "S.H.A.R.P"],
      tips: ["Engage in group discussions", "Deliver clear presentations", "Write structured essays"],
      goal: "Achieve Wizard status by demonstrating high-level fluency!" },
    { name: 'Wizard', tagline: 'Fluency & Mastery Achieved!', 
      colors: ['from-purple-600', 'via-violet-700', 'to-fuchsia-700'],
      bgPattern: 'from-purple-500/20 via-violet-500/20 to-fuchsia-500/20',
      description: "The highest level where students achieve excellence across all English skills.",
      modules: ["Creative Writing", "Grammar & Vocabulary", "Advanced Reading & Speaking", "Spelling Mastery"],
      tips: ["Write imaginative stories", "Lead class discussions", "Master complex spelling and grammar"],
      goal: "Stay at Wizard Level & Beyond! Inspire and mentor others!" }
  ],
  "Class VI to X": [
    { name: 'Rookie', tagline: 'Exploring New Horizons!', 
      colors: ['from-red-600', 'via-rose-600', 'to-pink-700'],
      bgPattern: 'from-red-500/20 via-rose-500/20 to-pink-500/20',
      description: "Students refine fundamental skills and expand their analytical knowledge.",
      modules: ["Grammar", "Reading", "Vocabulary", "Spelling"],
      tips: ["Master complex sentence structures", "Read young adult novels", "Build academic vocabulary systematically"],
      goal: "Rank up to Racer by achieving strong command over sentence formation and analysis!" },
    { name: 'Racer', tagline: 'Speeding Towards Excellence!', 
      colors: ['from-orange-500', 'via-yellow-500', 'to-amber-600'],
      bgPattern: 'from-orange-400/20 via-yellow-400/20 to-amber-400/20',
      description: "Develop analytical thinking, writing fluency, and advanced comprehension skills.",
      modules: ["Writing", "Listening", "S.H.A.R.P", "Pronunciation"],
      tips: ["Analyze texts for deeper meaning", "Practice formal presentations", "Master advanced word relationships"],
      goal: "Become a Master by enhancing analytical writing and comprehension!" },
    { name: 'Master', tagline: 'Precision in Expression!', 
      colors: ['from-teal-500', 'via-cyan-600', 'to-blue-600'],
      bgPattern: 'from-teal-400/20 via-cyan-400/20 to-blue-400/20',
      description: "Sharpen linguistic precision, develop critical thinking, and perfect grammar usage.",
      modules: ["Reading", "Grammar", "Writing", "Vocabulary"],
      tips: ["Develop thesis-driven analytical essays", "Master literary devices", "Use sophisticated vocabulary"],
      goal: "Rank up to Prodigy by mastering complex writing structures and critical analysis!" },
    { name: 'Prodigy', tagline: 'Mastering Advanced English!', 
      colors: ['from-indigo-600', 'via-blue-700', 'to-cyan-700'],
      bgPattern: 'from-indigo-500/20 via-blue-500/20 to-cyan-500/20',
      description: "Become proficient in academic writing, formal debate, and sophisticated literary analysis.",
      modules: ["Listening", "Pronunciation", "Advanced Writing", "S.H.A.R.P"],
      tips: ["Participate in formal debates", "Analyze complex literary works", "Write research-based academic papers"],
      goal: "Achieve Wizard status by excelling in literature, formal communication, and persuasive writing!" },
    { name: 'Wizard', tagline: 'Language Mastery at its Finest!', 
      colors: ['from-violet-700', 'via-purple-800', 'to-indigo-800'],
      bgPattern: 'from-violet-600/20 via-purple-600/20 to-indigo-600/20',
      description: "Attain complete fluency, master persuasive communication, and demonstrate expertise in advanced English concepts.",
      modules: ["Creative & Academic Writing", "Grammar & Advanced Vocabulary", "Public Speaking & Pronunciation", "Critical Reading & Spelling Mastery"],
      tips: ["Compose compelling speeches and essays", "Lead literary discussions", "Mentor junior students in language skills"],
      goal: "Stay at Wizard Level & Beyond! Become a communication leader and inspire excellence!" }
  ]
};

// Module Distribution Analysis
const moduleAnalysis = {
  totalModules: 8,
  modules: ["Spelling", "Reading", "Pronunciation", "Grammar", "Writing", "Listening", "Vocabulary", "S.H.A.R.P"],
  distribution: {
    "Class I & II": {
      "Rookie": ["Spelling", "Reading", "Pronunciation", "Vocabulary"],
      "Racer": ["Grammar", "Writing", "S.H.A.R.P", "Listening"],
      "Master": ["Writing", "Pronunciation", "Vocabulary", "Reading"],
      "Prodigy": ["S.H.A.R.P", "Listening", "Grammar", "Spelling"],
      "Wizard": ["All Modules Combined", "Writing", "Grammar & Vocabulary", "Reading & Speaking"]
    },
    "Class III to V": {
      "Rookie": ["Grammar", "Reading", "Vocabulary", "Spelling"],
      "Racer": ["Writing", "Listening", "S.H.A.R.P", "Pronunciation"],
      "Master": ["Reading", "Grammar", "Writing", "Vocabulary"],
      "Prodigy": ["Listening", "Pronunciation", "Advanced Writing", "S.H.A.R.P"],
      "Wizard": ["Creative Writing", "Grammar & Vocabulary", "Advanced Reading & Speaking", "Spelling Mastery"]
    },
    "Class VI to X": {
      "Rookie": ["Grammar", "Reading", "Vocabulary", "Spelling"],
      "Racer": ["Writing", "Listening", "S.H.A.R.P", "Pronunciation"],
      "Master": ["Reading", "Grammar", "Writing", "Vocabulary"],
      "Prodigy": ["Listening", "Pronunciation", "Advanced Writing", "S.H.A.R.P"],
      "Wizard": ["Creative & Academic Writing", "Grammar & Advanced Vocabulary", "Public Speaking & Pronunciation", "Critical Reading & Spelling Mastery"]
    }
  }
};

export { levelData, moduleAnalysis };
